import type { Metadata } from "next";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Preloader from "@/components/Preloader/Preloader";

export const metadata: Metadata = {
  title: 'Аудиторская группа "Аземша и партнеры"',
  description: "Generated by create next app",
};

export default function MainLayout({
  children, 
}: {
  children: React.ReactNode;
}) {
  return (
        <>
      {/* <Preloader/> */}
        <Header />
        {children}
        <Footer />
        </>
  );
}
