-- AlterTable
ALTER TABLE "reports" ALTER COLUMN "money_sso" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "money_audit" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "money_all" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "money_other" SET DATA TYPE DOUBLE PRECISION;
